### ISSUE TITLE
Using it outside of Hubot

### ISSUE THREAD

**Issue by imraansarwar** [lmarkus/hubot-conversation#14]
Hi,
Can this conversation be used outside of Hubot?
I'm doing a twitter bot, I wonder if this can be used to manage the conversations there.

Regards,
Imran

**Comment by lmarkus** [comment]
This module is very specific to the Hubot framework.
That said, the Hubot framework relies on adapters to connect to different chat systems.
A quick google search reveals one for twitter: https://github.com/MathildeLemee/hubot-twitter so you could, in theory, create a hubot bot for twitter.
