### ISSUE TITLE
unable to load conversation

### ISSUE THREAD

**Issue by humblemink** [lmarkus/hubot-conversation#17]
Might seem trivial, but i think Dialog.js has a missing parenthesis at line 123
 if (choices.length > 0) worked for me instead of the original 
 if choices.length > 0....

**Comment by lmarkus** [comment]
You are right, however, that was just added via #15 and I haven't published an updated version with that recent change yet to npm

Unless you're working directly with the code from GitHub, that shouldn't be affecting you.
