### ISSUE TITLE
no method debuglog

### ISSUE THREAD

**Issue by beeva-nievesabalos** [lmarkus/hubot-conversation#5]
I'm just trying to use hubot-conversation in my bot and I can't make it work:

```
TypeError: Object #<Object> has no method 'debuglog'
  at Object.<anonymous> (/home/mybot/node_modules/hubot-conversation/lib/Dialog.js:8:18)

```

I've tried installing the npm package called 'util'. Any idea? 

Thanks in advance!

**Comment by lmarkus** [comment]
Are you on node <=v0.10.x?
Looks like util.debuglog was unavailable then.
If you can upgrade, that will fix it for you, otherwise, I'll write a shield for it in the next couple of days.

**Comment by beeva-nievesabalos** [comment]
Thank you very much! It solved upgrading node version.

**Comment by lmarkus** [comment]
Good to hear.
Since some people can't upgrade for various reasons, and this was relatively easy, I made it compatible with Node v0.10.x

Published @1.0.3

**Comment by angelalukic** [comment]
Sorry to bump a closed & dead thread but I'm having this problem. I'm on v4.2.6

I followed this guide to update to v 6.2.2, however I'm still getting the same error:
http://tecadmin.net/upgrade-nodejs-via-npm/#

**Comment by angelalukic** [comment]
Oops nvm turns out I copied 'hubot-conversation' to the wrong node-modules folder? Instead of the one in user I put it in the one within my project and now all seems to be working. Whoopsie
I got my epiphany from this if it helps anyone: http://stackoverflow.com/a/38218364/6633633

**Comment by lmarkus** [comment]
My favorite kind of problem
