### ISSUE TITLE
Wrong prop name in the npm page example

### ISSUE THREAD

**Issue by cluk3** [lmarkus/hubot-conversation#7]
Hi! Just wanted to tell you that at https://www.npmjs.com/package/hubot-conversation in the example code `dialog.dialogTimeout` property is called `dialog.timeout`

**Comment by lmarkus** [comment]
Thanks for pointing it out.

**Comment by bradam12** [comment]
dialog.dialogTimeout is what worked for me, which is what is at the bottom of the readme file, and at https://github.com/lmarkus/hubot-conversation/blob/master/lib/Dialog.js#L120-L122.  That's why I put in #6
